// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "awslabs/aws-eks-cluster-controller/pkg/clientset/versioned/typed/cluster/v1alpha1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeClusterV1alpha1 struct {
	*testing.Fake
}

func (c *FakeClusterV1alpha1) ControlPlanes(namespace string) v1alpha1.ControlPlaneInterface {
	return &FakeControlPlanes{c, namespace}
}

func (c *FakeClusterV1alpha1) EKSs(namespace string) v1alpha1.EKSInterface {
	return &FakeEKSs{c, namespace}
}

func (c *FakeClusterV1alpha1) NodeGroups(namespace string) v1alpha1.NodeGroupInterface {
	return &FakeNodeGroups{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeClusterV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
